set(OPTION_DEFAULT ON)
set(OPTION_CLIENT_DEFAULT ON)
set(OPTION_SERVER_DEFAULT OFF)

define_channel_options(
  NAME "rdptun"
  TYPE "dynamic"
  DESCRIPTION "Raw IP packets over an RDP dynamic virtual channel"
  SPECIFICATIONS "private"
  DEFAULT ${OPTION_DEFAULT}
  CLIENT_DEFAULT ${OPTION_CLIENT_DEFAULT}
  SERVER_DEFAULT ${OPTION_SERVER_DEFAULT}
)
